 //
// GENERATED CODE DO NOT UPDATE
// Telosys Template : csharp-backend / Controller / Xxxcontroller.vm
// C# class for entity "Brand" 
// Created on 2022-11-25 ( Date ISO 2022-11-25 - Time 15:32:57 )
// Generated by Telosys Tools Generator ( version 4.0.0 )
//

using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

using CarModel.Models;
using CarModel.ViewModels;
using CarModel.Entities;

namespace CarModel.Controllers
{
    /// <summary>
    /// Web service  Brand 
    /// Ici on assure le routage vers une URL qui contiendra la dénomination : /api/v1/ et le nom du controleur 
    /// comme d'habitude .NET prendra le soin de supprimer tout seul le texte "Controller" sur le nom du service
    /// 
    /// ApiController : action des controles d'erreur
    /// </summary>
    [Route("api/v1/[controller]")]
    [ApiController]
	public class BrandController : ControllerBase
	{
		private EntitiesDbContext _context { get; set; }		

        /// <summary>
        /// Constructeur
        /// </summary>
		public BrandController()
		{
			_context = new EntitiesDbContext();
		}

        /// <summary>
        /// READ Liste Brand 
        /// Retourne une liste des Brand avec un gestion de la pagination.
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="pageSize">Taille de la page.</param>   
        /// <param name="pageIndex">Index du premiere elements dans la page.</param>   
        /// <response code="200">OK, renvois de la liste demandé.</response>
        /// <response code="404">Erreur, non trouvé la liste est vide.</response>
        [HttpGet()]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
		public ActionResult<IEnumerable<Brand>> GetBrands([FromQuery]int pageSize = 10,[FromQuery] int pageIndex = 0)
		{
            // FIND ALL with paging
			var lstResult = _context.Brands
                                    .Skip(pageSize * pageIndex)
                                    .Take(pageSize)
                                    .ToList();
            return Ok(lstResult);
		}
		
        /// <summary>
        /// READ Brand
        /// Retourne un Brand a partir de son identifiant ID
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="id">id du Brand doit être supérieur à 0.</param>   
        /// <response code="200">OK, le Brand est retourné.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Brand n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpGet()]
        [Route("{id}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status400BadRequest)] 
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
        [ProducesResponseType(StatusCodes.Status200OK)]
        public ActionResult<Brand> GetBrand(string Code)
        {
            // READ
            Brand? ReadData = _context.Brands
                                                .FirstOrDefault(item => item.Code == Code);
            if (ReadData == null) 
                return NotFound($"Non trouvé avec l'ID = {Code}");

            return Ok(ReadData);
        }

        /// <summary>
        /// CREATE Brand
        /// Creation d'un Brand dans la listes des  items
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="createVM">Données du Brand a ajouter.</param>   
        /// <response code="200">OK, le Brand est retourné.</response>
        [HttpPost()]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public ActionResult<Brand> CreateBrand([FromBody]BrandCreateViewModel createVM)
        {
            // INSTANCE CREATE
			var ToCreate = new Brand();

			// KEYS
			ToCreate.Code = Guid.NewGuid().ToString();
			// DATAS
			ToCreate.Name = createVM.Name;
			ToCreate.Company_oid = createVM.Company_oid;
			// SAVE
			_context.Brands.Add( ToCreate );
			_context.SaveChanges();

            return Ok(ToCreate);
        }

        /// <summary>
        /// UPDATE Brand
        /// Mise a jour d'un Brand dans la liste des Brands.
        /// La mise a jour est reéalisé à partir de l'ID
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="id">id du Brand doit être supérieur à 0.</param>   
        /// <param name="dataToUpdate">Données du Brand a mettre a jour.</param>   
        /// <response code="200">OK, le Brand est mise a jour.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Brand n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpPut()]
        [Route("{id}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)] 
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
        public ActionResult  UpdateBrand(string Code, [FromBody]BrandUpdateViewModel updateVM)
        {
            // FIND ITEM TO UPDATE
			Brand ToUpdateBrand = _context.Brands
                                                .FirstOrDefault(x => x.Code == updateVM.Code);
            if (ToUpdateBrand == null)
                return NotFound($"Non trouvé avec l'ID = {Code}");

			// KEYS
			ToUpdateBrand.Code = updateVM.Code;
			// DATAS
			ToUpdateBrand.Name = updateVM.Name;
			ToUpdateBrand.Company_oid = updateVM.Company_oid;
			// SAVE
			_context.SaveChanges();

            return Ok();
        }

        /// <summary>
        /// DELETE Brand
        /// Supprimer un Brand a partir de son identifiant ID
        /// </summary>
        /// <param name="id">id du Brand doit être supérieur à 0.</param>   
        /// <response code="200">OK, le Brand est supprimé.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Brand n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpDelete()]
        [Route("{id}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public ActionResult DeleteBrand(string Code)
        {
			// FIND ITEM to DELETE 
			Brand? ToDelete = _context.Brands
                                            .FirstOrDefault(x => x.Code == Code);
			// DELETE 
            if (ToDelete == null)
                return NotFound($"Non trouvé avec l'ID = {Code}");
			_context.Brands.Remove(ToDelete);

			// SAVE
			_context.SaveChanges();

            return Ok();
        }
	}
}
