 //
// GENERATED CODE DO NOT UPDATE
// Telosys Template : csharp-backend / Controller / Xxxcontroller.vm
// C# class for entity "Car" 
// Created on 2022-11-25 ( Date ISO 2022-11-25 - Time 15:32:57 )
// Generated by Telosys Tools Generator ( version 4.0.0 )
//

using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

using CarModel.Models;
using CarModel.ViewModels;
using CarModel.Entities;

namespace CarModel.Controllers
{
    /// <summary>
    /// Web service  Car 
    /// Ici on assure le routage vers une URL qui contiendra la dénomination : /api/v1/ et le nom du controleur 
    /// comme d'habitude .NET prendra le soin de supprimer tout seul le texte "Controller" sur le nom du service
    /// 
    /// ApiController : action des controles d'erreur
    /// </summary>
    [Route("api/v1/[controller]")]
    [ApiController]
	public class CarController : ControllerBase
	{
		private EntitiesDbContext _context { get; set; }		

        /// <summary>
        /// Constructeur
        /// </summary>
		public CarController(EntitiesDbContext context)
		{
			_context = context;
		}

        /// <summary>
        /// READ Liste Car 
        /// Retourne une liste des Car avec un gestion de la pagination.
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="pageSize">Taille de la page.</param>   
        /// <param name="pageIndex">Index du premiere elements dans la page.</param>   
        /// <response code="200">OK, renvois de la liste demandé.</response>
        /// <response code="404">Erreur, non trouvé la liste est vide.</response>
        [HttpGet()]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
		public ActionResult<IEnumerable<Car>> GetCars([FromQuery]int pageSize = 10,[FromQuery] int pageIndex = 0)
		{
            // FIND ALL with paging
			var lstResult = _context.Cars
                                    .Skip(pageSize * pageIndex)
                                    .Take(pageSize)
                                    .ToList();
            return Ok(lstResult);
		}
		
        /// <summary>
        /// READ Car
        /// Retourne un Car a partir de son identifiant ID
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="id">id du Car doit être supérieur à 0.</param>   
        /// <response code="200">OK, le Car est retourné.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Car n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpGet()]
        [Route("{id}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status400BadRequest)] 
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
        [ProducesResponseType(StatusCodes.Status200OK)]
        public ActionResult<Car> GetCar(long oid)
        {
            // READ
            Car? ReadData = _context.Cars
                                                .FirstOrDefault(item => item.oid == oid);
            if (ReadData == null) 
                return NotFound($"Non trouvé avec l'ID = {oid}");

            return Ok(ReadData);
        }

        /// <summary>
        /// CREATE Car
        /// Creation d'un Car dans la listes des  items
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="createVM">Données du Car a ajouter.</param>   
        /// <response code="200">OK, le Car est retourné.</response>
        [HttpPost()]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public ActionResult<Car> CreateCar([FromBody]CarCreateViewModel createVM)
        {
            // INSTANCE CREATE
			var ToCreate = new Car();

			// KEYS
			// DATAS
			ToCreate.Name = createVM.Name;
			ToCreate.Year = createVM.Year;
			ToCreate.Price = createVM.Price;
			ToCreate.BrandCode = createVM.BrandCode;
			ToCreate.Driver_oid = createVM.Driver_oid;
			// SAVE
			_context.Cars.Add( ToCreate );
			_context.SaveChanges();

            return Ok(ToCreate);
        }

        /// <summary>
        /// UPDATE Car
        /// Mise a jour d'un Car dans la liste des Cars.
        /// La mise a jour est reéalisé à partir de l'ID
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="id">id du Car doit être supérieur à 0.</param>   
        /// <param name="dataToUpdate">Données du Car a mettre a jour.</param>   
        /// <response code="200">OK, le Car est mise a jour.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Car n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpPut()]
        [Route("{id}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)] 
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
        public ActionResult  UpdateCar(long oid, [FromBody]CarUpdateViewModel updateVM)
        {
            // FIND ITEM TO UPDATE
			Car ToUpdateCar = _context.Cars
                                                .FirstOrDefault(x => x.oid == updateVM.oid);
            if (ToUpdateCar == null)
                return NotFound($"Non trouvé avec l'ID = {oid}");

			// KEYS
			ToUpdateCar.oid = updateVM.oid;
			// DATAS
			ToUpdateCar.Name = updateVM.Name;
			ToUpdateCar.Year = updateVM.Year;
			ToUpdateCar.Price = updateVM.Price;
			ToUpdateCar.BrandCode = updateVM.BrandCode;
			ToUpdateCar.Driver_oid = updateVM.Driver_oid;
			// SAVE
			_context.SaveChanges();

            return Ok();
        }

        /// <summary>
        /// DELETE Car
        /// Supprimer un Car a partir de son identifiant ID
        /// </summary>
        /// <param name="id">id du Car doit être supérieur à 0.</param>   
        /// <response code="200">OK, le Car est supprimé.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Car n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpDelete()]
        [Route("{id}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public ActionResult DeleteCar(long oid)
        {
			// FIND ITEM to DELETE 
			Car? ToDelete = _context.Cars
                                            .FirstOrDefault(x => x.oid == oid);
			// DELETE 
            if (ToDelete == null)
                return NotFound($"Non trouvé avec l'ID = {oid}");
			_context.Cars.Remove(ToDelete);

			// SAVE
			_context.SaveChanges();

            return Ok();
        }
	}
}
