 //
// GENERATED CODE DO NOT UPDATE
// Telosys Template : csharp-backend / Controller / Xxxcontroller.vm
// C# class for entity "Company" 
// Created on 2022-11-25 ( Date ISO 2022-11-25 - Time 15:32:57 )
// Generated by Telosys Tools Generator ( version 4.0.0 )
//

using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

using CarModel.Models;
using CarModel.ViewModels;
using CarModel.Entities;

namespace CarModel.Controllers
{
    /// <summary>
    /// Web service  Company 
    /// Ici on assure le routage vers une URL qui contiendra la dénomination : /api/v1/ et le nom du controleur 
    /// comme d'habitude .NET prendra le soin de supprimer tout seul le texte "Controller" sur le nom du service
    /// 
    /// ApiController : action des controles d'erreur
    /// </summary>
    [Route("api/v1/[controller]")]
    [ApiController]
	public class CompanyController : ControllerBase
	{
		private EntitiesDbContext _context { get; set; }		

        /// <summary>
        /// Constructeur
        /// </summary>
		public CompanyController(EntitiesDbContext __context)
		{
            //_context = new EntitiesDbContext();
            _context = __context;

        }

        /// <summary>
        /// READ Liste Company 
        /// Retourne une liste des Company avec un gestion de la pagination.
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="pageSize">Taille de la page.</param>   
        /// <param name="pageIndex">Index du premiere elements dans la page.</param>   
        /// <response code="200">OK, renvois de la liste demandé.</response>
        /// <response code="404">Erreur, non trouvé la liste est vide.</response>
        [HttpGet()]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
		public ActionResult<IEnumerable<Company>> GetCompanys([FromQuery]int pageSize = 10,[FromQuery] int pageIndex = 0)
		{
            // FIND ALL with paging
			var lstResult = _context.Companys
                                    .Skip(pageSize * pageIndex)
                                    .Take(pageSize)
                                    .ToList();
            return Ok(lstResult);
		}
		
        /// <summary>
        /// READ Company
        /// Retourne un Company a partir de son identifiant ID
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="id">id du Company doit être supérieur à 0.</param>   
        /// <response code="200">OK, le Company est retourné.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Company n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpGet()]
        [Route("{id}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status400BadRequest)] 
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
        [ProducesResponseType(StatusCodes.Status200OK)]
        public ActionResult<Company> GetCompany(long oid)
        {
            // READ
            Company? ReadData = _context.Companys
                                                .FirstOrDefault(item => item.oid == oid);
            if (ReadData == null) 
                return NotFound($"Non trouvé avec l'ID = {oid}");

            return Ok(ReadData);
        }

        /// <summary>
        /// CREATE Company
        /// Creation d'un Company dans la listes des  items
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="createVM">Données du Company a ajouter.</param>   
        /// <response code="200">OK, le Company est retourné.</response>
        [HttpPost()]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public ActionResult<Company> CreateCompany([FromBody]CompanyCreateViewModel createVM)
        {
            // INSTANCE CREATE
			var ToCreate = new Company();

			// KEYS
			// DATAS
			ToCreate.name = createVM.name;
			// SAVE
			_context.Companys.Add( ToCreate );
			_context.SaveChanges();

            return Ok(ToCreate);
        }

        /// <summary>
        /// UPDATE Company
        /// Mise a jour d'un Company dans la liste des Companys.
        /// La mise a jour est reéalisé à partir de l'ID
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="id">id du Company doit être supérieur à 0.</param>   
        /// <param name="dataToUpdate">Données du Company a mettre a jour.</param>   
        /// <response code="200">OK, le Company est mise a jour.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Company n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpPut()]
        [Route("{id}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)] 
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
        public ActionResult  UpdateCompany(long oid, [FromBody]CompanyUpdateViewModel updateVM)
        {
            // FIND ITEM TO UPDATE
			Company ToUpdateCompany = _context.Companys
                                                .FirstOrDefault(x => x.oid == updateVM.oid);
            if (ToUpdateCompany == null)
                return NotFound($"Non trouvé avec l'ID = {oid}");

			// KEYS
			ToUpdateCompany.oid = updateVM.oid;
			// DATAS
			ToUpdateCompany.name = updateVM.name;
			// SAVE
			_context.SaveChanges();

            return Ok();
        }

        /// <summary>
        /// DELETE Company
        /// Supprimer un Company a partir de son identifiant ID
        /// </summary>
        /// <param name="id">id du Company doit être supérieur à 0.</param>   
        /// <response code="200">OK, le Company est supprimé.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Company n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpDelete()]
        [Route("{id}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public ActionResult DeleteCompany(long oid)
        {
			// FIND ITEM to DELETE 
			Company? ToDelete = _context.Companys
                                            .FirstOrDefault(x => x.oid == oid);
			// DELETE 
            if (ToDelete == null)
                return NotFound($"Non trouvé avec l'ID = {oid}");
			_context.Companys.Remove(ToDelete);

			// SAVE
			_context.SaveChanges();

            return Ok();
        }
	}
}
