 //
// GENERATED CODE DO NOT UPDATE
// Telosys Template : csharp-backend / Controller / Xxxcontroller.vm
// C# class for entity "Driver" 
// Created on 2022-11-25 ( Date ISO 2022-11-25 - Time 15:32:57 )
// Generated by Telosys Tools Generator ( version 4.0.0 )
//

using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

using CarModel.Models;
using CarModel.ViewModels;
using CarModel.Entities;

namespace CarModel.Controllers
{
    /// <summary>
    /// Web service  Driver 
    /// Ici on assure le routage vers une URL qui contiendra la dénomination : /api/v1/ et le nom du controleur 
    /// comme d'habitude .NET prendra le soin de supprimer tout seul le texte "Controller" sur le nom du service
    /// 
    /// ApiController : action des controles d'erreur
    /// </summary>
    [Route("api/v1/[controller]")]
    [ApiController]
	public class DriverController : ControllerBase
	{
		private EntitiesDbContext _context { get; set; }		

        /// <summary>
        /// Constructeur
        /// </summary>
		public DriverController()
		{
			_context = new EntitiesDbContext();
		}

        /// <summary>
        /// READ Liste Driver 
        /// Retourne une liste des Driver avec un gestion de la pagination.
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="pageSize">Taille de la page.</param>   
        /// <param name="pageIndex">Index du premiere elements dans la page.</param>   
        /// <response code="200">OK, renvois de la liste demandé.</response>
        /// <response code="404">Erreur, non trouvé la liste est vide.</response>
        [HttpGet()]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
		public ActionResult<IEnumerable<Driver>> GetDrivers([FromQuery]int pageSize = 10,[FromQuery] int pageIndex = 0)
		{
            // FIND ALL with paging
			var lstResult = _context.Drivers
                                    .Skip(pageSize * pageIndex)
                                    .Take(pageSize)
                                    .ToList();
            return Ok(lstResult);
		}
		
        /// <summary>
        /// READ Driver
        /// Retourne un Driver a partir de son identifiant ID
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="id">id du Driver doit être supérieur à 0.</param>   
        /// <response code="200">OK, le Driver est retourné.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Driver n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpGet()]
        [Route("{id}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status400BadRequest)] 
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
        [ProducesResponseType(StatusCodes.Status200OK)]
        public ActionResult<Driver> GetDriver(long oid)
        {
            // READ
            Driver? ReadData = _context.Drivers
                                                .FirstOrDefault(item => item.oid == oid);
            if (ReadData == null) 
                return NotFound($"Non trouvé avec l'ID = {oid}");

            return Ok(ReadData);
        }

        /// <summary>
        /// CREATE Driver
        /// Creation d'un Driver dans la listes des  items
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="createVM">Données du Driver a ajouter.</param>   
        /// <response code="200">OK, le Driver est retourné.</response>
        [HttpPost()]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public ActionResult<Driver> CreateDriver([FromBody]DriverCreateViewModel createVM)
        {
            // INSTANCE CREATE
			var ToCreate = new Driver();

			// KEYS
			// DATAS
			ToCreate.FirstName = createVM.FirstName;
			ToCreate.LastName = createVM.LastName;
			ToCreate.BirthDate = createVM.BirthDate;
			ToCreate.Comment = createVM.Comment;
			// SAVE
			_context.Drivers.Add( ToCreate );
			_context.SaveChanges();

            return Ok(ToCreate);
        }

        /// <summary>
        /// UPDATE Driver
        /// Mise a jour d'un Driver dans la liste des Drivers.
        /// La mise a jour est reéalisé à partir de l'ID
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="id">id du Driver doit être supérieur à 0.</param>   
        /// <param name="dataToUpdate">Données du Driver a mettre a jour.</param>   
        /// <response code="200">OK, le Driver est mise a jour.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Driver n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpPut()]
        [Route("{id}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)] 
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
        public ActionResult  UpdateDriver(long oid, [FromBody]DriverUpdateViewModel updateVM)
        {
            // FIND ITEM TO UPDATE
			Driver ToUpdateDriver = _context.Drivers
                                                .FirstOrDefault(x => x.oid == updateVM.oid);
            if (ToUpdateDriver == null)
                return NotFound($"Non trouvé avec l'ID = {oid}");

			// KEYS
			ToUpdateDriver.oid = updateVM.oid;
			// DATAS
			ToUpdateDriver.FirstName = updateVM.FirstName;
			ToUpdateDriver.LastName = updateVM.LastName;
			ToUpdateDriver.BirthDate = updateVM.BirthDate;
			ToUpdateDriver.Comment = updateVM.Comment;
			// SAVE
			_context.SaveChanges();

            return Ok();
        }

        /// <summary>
        /// DELETE Driver
        /// Supprimer un Driver a partir de son identifiant ID
        /// </summary>
        /// <param name="id">id du Driver doit être supérieur à 0.</param>   
        /// <response code="200">OK, le Driver est supprimé.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Driver n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpDelete()]
        [Route("{id}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public ActionResult DeleteDriver(long oid)
        {
			// FIND ITEM to DELETE 
			Driver? ToDelete = _context.Drivers
                                            .FirstOrDefault(x => x.oid == oid);
			// DELETE 
            if (ToDelete == null)
                return NotFound($"Non trouvé avec l'ID = {oid}");
			_context.Drivers.Remove(ToDelete);

			// SAVE
			_context.SaveChanges();

            return Ok();
        }
	}
}
