 //
// C# class for DTO "Comment" 
// Created on 2023-02-19 ( Date ISO 2023-02-19 - Time 22:05:48 )
// Generated by Telosys Tools Generator ( version 4.0.0 )
//

using System;
using System.Collections.Generic;
using System.Linq;

using CarModel.Models;
using CarModel.Entities;

namespace CarModel.DTO
{
	public class CommentUpdateDTO
	{
		public long oid { get; set; } 
 
		public string comment { get; set; } 
 
		public long Post_oid { get; set; }
 
     		
		public CommentUpdateDTO()
		{

		}
		
		public CommentUpdateDTO(Comment Comment)
		{
			oid =  Comment.oid;
 
			comment = Comment.comment;
 
			Post_oid = Comment.Post_oid;
 		}
	}
}
