 //
// C# class for DTO "Comment" 
// Created on 2023-02-18 ( Date ISO 2023-02-18 - Time 18:39:21 )
// Generated by Telosys Tools Generator ( version 4.0.0 )
//

using System;
using System.Collections.Generic;
using System.Linq;

using CarModel.Models;
using CarModel.Entities;

namespace CarModel.DTO
{
	public class CommentCreateDTO
	{	
		// data Fields
		public string comment { get; set; } 
 
		// Links Fields
		public long Post_oid { get; set; }
 

		public CommentCreateDTO()
		{

		}

		public CommentCreateDTO(Comment Comment)
		{

			comment = Comment.comment;
 
			Post_oid = Comment.Post_oid;
 
		}

	}
}
