 //
// C# class for DTO "Post" 
// Created on 2023-02-19 ( Date ISO 2023-02-19 - Time 22:05:48 )
// Generated by Telosys Tools Generator ( version 4.0.0 )
//

using System;
using System.Collections.Generic;
using System.Linq;

using CarModel.Models;
using CarModel.Entities;

namespace CarModel.DTO
{
	public class PostCreateDTO
	{	
		// data Fields
		public string Title { get; set; } 
		public string Description { get; set; } 
 
		// Links Fields
 

		public PostCreateDTO()
		{

		}

		public PostCreateDTO(Post Post)
		{

			Title = Post.Title;
			Description = Post.Description;
 
 
		}

	}
}
