 //
// C# class for DTO "Post" 
// Created on 2023-02-19 ( Date ISO 2023-02-19 - Time 22:05:48 )
// Generated by Telosys Tools Generator ( version 4.0.0 )
//

using System;
using System.Collections.Generic;
using System.Linq;

using CarModel.Models;
using CarModel.Entities;

namespace CarModel.DTO
{
	public class PostUpdateDTO
	{
		public long oid { get; set; } 
 
		public string Title { get; set; } 
		public string Description { get; set; } 
 
 
 		
		public PostUpdateDTO()
		{

		}
		
		public PostUpdateDTO(Post Post)
		{
			oid =  Post.oid;
 
			Title = Post.Title;
			Description = Post.Description;
 
 		}
	}
}
