 //
// GENERATED CODE DO NOT UPDATE
// Telosys Template : csharp-backend / Controller / Xxxcontroller.DTO
// C# class for entity "Comment" 
// Created on 2023-02-19 ( Date ISO 2023-02-19 - Time 22:05:48 )
// Generated by Telosys Tools Generator ( version 4.0.0 )
//

using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

using CarModel.Models;
using CarModel.DTO;
using CarModel.Entities;

namespace CarModel.Controllers
{
    /// <summary>
    /// Web service  Comment 
    /// Ici on assure le routage vers une URL qui contiendra la dénomination : /api/v1/ et le nom du controleur 
    /// comme d'habitude .NET prendra le soin de supprimer tout seul le texte "Controller" sur le nom du service
    /// 
    /// ApiController : action des controles d'erreur
    /// </summary>
    [Route("api/v1/[controller]")]
    [ApiController]
	public class CommentController : ControllerBase
	{
		private EntitiesDbContext _context { get; set; }		

        /// <summary>
        /// Constructeur
        /// </summary>
		public CommentController()
		{
			_context = new EntitiesDbContext();
		}

        /// <summary>
        /// READ Liste Comment 
        /// Retourne une liste des Comment avec un gestion de la pagination.
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="pageSize">Taille de la page.</param>   
        /// <param name="pageIndex">Index du premiere elements dans la page.</param>   
        /// <response code="200">OK, renvois de la liste demandé.</response>
        /// <response code="404">Erreur, non trouvé la liste est vide.</response>
        [HttpGet()]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
		public ActionResult<IEnumerable<Comment>> GetComments([FromQuery]int pageSize = 10,[FromQuery] int pageIndex = 0)
		{
            // FIND ALL with paging
			var lstResult = _context.Comments
                                    .Skip(pageSize * pageIndex)
                                    .Take(pageSize)
                                    .ToList();
            return Ok(lstResult);
		}
		
        /// <summary>
        /// READ Comment
        /// Retourne un Comment a partir de son identifiant ID
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="id">id du Comment doit être supérieur à 0.</param>   
        /// <response code="200">OK, le Comment est retourné.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Comment n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpGet()]
        [Route("{oid}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status400BadRequest)] 
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
        [ProducesResponseType(StatusCodes.Status200OK)]
        public ActionResult<Comment> GetComment(long oid)
        {
            // READ
            Comment? ReadData = _context.Comments
                                                .FirstOrDefault(item => item.oid == oid);
            if (ReadData == null) 
                return NotFound($"Non trouvé avec l'ID = {oid}");

            return Ok(ReadData);
        }

        /// <summary>
        /// CREATE Comment
        /// Creation d'un Comment dans la listes des  items
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="createDTO">Données du Comment a ajouter.</param>   
        /// <response code="200">OK, le Comment est retourné.</response>
        [HttpPost()]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public ActionResult<Comment> CreateComment([FromBody]CommentCreateDTO createDTO)
        {
            // INSTANCE CREATE
			var ToCreate = new Comment();

			// KEYS
			// DATAS
			ToCreate.comment = createDTO.comment;
			ToCreate.Post_oid = createDTO.Post_oid;
			// SAVE
			_context.Comments.Add( ToCreate );
			_context.SaveChanges();

            return Ok(ToCreate);
        }

        /// <summary>
        /// UPDATE Comment
        /// Mise a jour d'un Comment dans la liste des Comments.
        /// La mise a jour est reéalisé à partir de l'ID
        /// </summary>
        /// <remarks>ici une remarque</remarks>
        /// <param name="id">id du Comment doit être supérieur à 0.</param>   
        /// <param name="dataToUpdate">Données du Comment a mettre a jour.</param>   
        /// <response code="200">OK, le Comment est mise a jour.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Comment n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpPut()]
        [Route("{oid}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)] 
        [ProducesResponseType(StatusCodes.Status404NotFound)] 
        public ActionResult  UpdateComment(long oid, [FromBody]CommentUpdateDTO updateDTO)
        {
            // FIND ITEM TO UPDATE
			Comment ToUpdateComment = _context.Comments
                                                .FirstOrDefault(x => x.oid == updateDTO.oid);
            if (ToUpdateComment == null)
                return NotFound($"Non trouvé avec l'ID = {oid}");

			// KEYS
			ToUpdateComment.oid = updateDTO.oid;
			// DATAS
			ToUpdateComment.comment = updateDTO.comment;
			ToUpdateComment.Post_oid = updateDTO.Post_oid;
			// SAVE
			_context.SaveChanges();

            return Ok();
        }

        /// <summary>
        /// DELETE Comment
        /// Supprimer un Comment a partir de son identifiant ID
        /// </summary>
        /// <param name="id">id du Comment doit être supérieur à 0.</param>   
        /// <response code="200">OK, le Comment est supprimé.</response>
        /// <response code="400">Mauvaise requete, id non invalide.</response>
        /// <response code="404">Erreur, le Comment n'est pas trouvé a partir de l'id spécifié.</response>
        [HttpDelete()]
        [Route("{oid}")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public ActionResult DeleteComment(long oid)
        {
			// FIND ITEM to DELETE 
			Comment? ToDelete = _context.Comments
                                            .FirstOrDefault(x => x.oid == oid);
			// DELETE 
            if (ToDelete == null)
                return NotFound($"Non trouvé avec l'ID = {oid}");
			_context.Comments.Remove(ToDelete);

			// SAVE
			_context.SaveChanges();

            return Ok();
        }
	}
}
