 //
// C# class for entity "Brand" 
// Created on 2022-11-25 ( Date ISO 2022-11-25 - Time 15:32:57 )
// Generated by Telosys Tools Generator ( version 4.0.0 )
//

using System;
using System.Collections.Generic;
using System.Linq;

using CarModel.Models;
using CarModel.Entities;

namespace CarModel.ViewModels
{
	public class BrandUpdateViewModel
	{
		public string Code { get; set; } 
 
		public string Name { get; set; } 
 
		public long Company_oid { get; set; }
 
     		
		public BrandUpdateViewModel()
		{

		}
		
		public BrandUpdateViewModel(Brand Brand)
		{
			Code =  Brand.Code;
 
			Name = Brand.Name;
 
			Company_oid = Brand.Company_oid;
 		}
	}
}
