 //
// C# class for entity "Brand" 
// Created on 2022-11-25 ( Date ISO 2022-11-25 - Time 15:32:57 )
// Generated by Telosys Tools Generator ( version 4.0.0 )
//

using System;
using System.Collections.Generic;
using System.Linq;

using CarModel.Models;
using CarModel.Entities;

namespace CarModel.ViewModels
{
	public class BrandCreateViewModel
	{	
		// data Fields
		public string Name { get; set; } 
 
		// Links Fields
		public long Company_oid { get; set; }
 

		public BrandCreateViewModel()
		{

		}

		public BrandCreateViewModel(Brand Brand)
		{

			Name = Brand.Name;
 
			Company_oid = Brand.Company_oid;
 
		}

	}
}
