 //
// C# class for entity "Driver" 
// Created on 2022-11-25 ( Date ISO 2022-11-25 - Time 15:32:57 )
// Generated by Telosys Tools Generator ( version 4.0.0 )
//

using System;
using System.Collections.Generic;
using System.Linq;

using CarModel.Models;
using CarModel.Entities;

namespace CarModel.ViewModels
{
	public class DriverUpdateViewModel
	{
		public long oid { get; set; } 
 
		public string FirstName { get; set; } 
		public string LastName { get; set; } 
		public DateTime BirthDate { get; set; } 
		public string Comment { get; set; } 
 
 
 		
		public DriverUpdateViewModel()
		{

		}
		
		public DriverUpdateViewModel(Driver Driver)
		{
			oid =  Driver.oid;
 
			FirstName = Driver.FirstName;
			LastName = Driver.LastName;
			BirthDate = Driver.BirthDate;
			Comment = Driver.Comment;
 
 		}
	}
}
