 //
// C# class for entity "Driver" 
// Created on 2022-11-25 ( Date ISO 2022-11-25 - Time 15:32:57 )
// Generated by Telosys Tools Generator ( version 4.0.0 )
//

using System;
using System.Collections.Generic;
using System.Linq;

using CarModel.Models;
using CarModel.Entities;

namespace CarModel.ViewModels
{
	public class DriverCreateViewModel
	{	
		// data Fields
		public string FirstName { get; set; } 
		public string LastName { get; set; } 
		public DateTime BirthDate { get; set; } 
		public string Comment { get; set; } 
 
		// Links Fields
 

		public DriverCreateViewModel()
		{

		}

		public DriverCreateViewModel(Driver Driver)
		{

			FirstName = Driver.FirstName;
			LastName = Driver.LastName;
			BirthDate = Driver.BirthDate;
			Comment = Driver.Comment;
 
 
		}

	}
}
