 //
// GENERATED CODE DO NOT UPDATE
// Telosys Template : csharp-backend / Entities / Xxx.vm
// C# class for entity "Brand" 
// Created on 2022-11-25 ( Date ISO 2022-11-25 - Time 15:32:57 )
// Generated by : csharp-backend 
// Generated by : Telosys Tools Generator 4.0.0
//

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;


namespace CarModel.Entities
{
	public class Brand
	{
		//--- KEY ATTRIBUTE 

		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.None)]
 		public string Code { get; set; }
  
		//--- DATA (NOT KEY and NOT LINK) ATTRIBUTES 

		public string Name { get; set; } 

		//--- LINKS ATTRIBUTES 

		[ForeignKey("Company")]
		public long Company_oid { get; set; }
		public Company Company { get; set; }
    		
		public Brand()
		{

		}

		public override string ToString()
		{
			return string.Empty  +    Name ;	
		}
	}

  
}
