 //
// GENERATED CODE DO NOT UPDATE
// Telosys Template : csharp-backend / Entities / Xxx.vm
// C# class for entity "Car" 
// Created on 2022-11-25 ( Date ISO 2022-11-25 - Time 15:32:57 )
// Generated by : csharp-backend 
// Generated by : Telosys Tools Generator 4.0.0
//

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;


namespace CarModel.Entities
{
	public class Car
	{
		//--- KEY ATTRIBUTE 

		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
 		public long oid { get; set; }
  
		//--- DATA (NOT KEY and NOT LINK) ATTRIBUTES 

		public string Name { get; set; } 
		public short Year { get; set; } 
		public float Price { get; set; } 

		//--- LINKS ATTRIBUTES 

		[ForeignKey("Brand")]
		public string BrandCode { get; set; }
		public Brand Brand { get; set; }

		[ForeignKey("Driver")]
		public long Driver_oid { get; set; }
		public Driver Driver { get; set; }
      		
		public Car()
		{

		}

		public override string ToString()
		{
			return string.Empty  +    Name + " " +   Year + " " +   Price ;	
		}
	}

   
}
